[behave]

# -----------------------------
# Execution
# -----------------------------
default_tags = ~@wip

# -----------------------------
# Console Output
# -----------------------------
show_skipped = false
show_timings = true
stdout_capture = true
stderr_capture = true

# -----------------------------
# Logging
# -----------------------------
logging_level = INFO

# -----------------------------
# JUnit Report
# -----------------------------
junit = true
junit_directory = reports/junit/

# -----------------------------
# Allure Report
# -----------------------------
format = allure_behave.formatter:AllureFormatter
outfiles = reports/allure-results